// <auto-generated />
using System;
using DAL.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DAL.Migrations
{
    [DbContext(typeof(BookFilghtsDbContext))]
    [Migration("20251205195710_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BAL.model.AppUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PassportNumber")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("Users", "Security");
                });

            modelBuilder.Entity("DAL.models.AddOn", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<short>("price")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.ToTable("AddOns");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Extra Baggage",
                            price = (short)150
                        },
                        new
                        {
                            Id = 4,
                            Name = "Priority Boarding",
                            price = (short)50
                        },
                        new
                        {
                            Id = 3,
                            Name = "Premium Meal",
                            price = (short)100
                        });
                });

            modelBuilder.Entity("DAL.models.Airline", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Airlines");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "EGY",
                            Name = "EgyptAir"
                        },
                        new
                        {
                            Id = 2,
                            Code = "EMR",
                            Name = "Emirates"
                        },
                        new
                        {
                            Id = 3,
                            Code = "QTR",
                            Name = "Qatar Airways"
                        },
                        new
                        {
                            Id = 4,
                            Code = "KSA",
                            Name = "KSA"
                        });
                });

            modelBuilder.Entity("DAL.models.Airplane", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AirlineId")
                        .HasColumnType("int");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<short>("SeatCapacity")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.HasIndex("AirlineId");

                    b.ToTable("Airplanes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AirlineId = 1,
                            Model = "Boeing 999",
                            SeatCapacity = (short)8
                        },
                        new
                        {
                            Id = 2,
                            AirlineId = 1,
                            Model = "Airbus A320",
                            SeatCapacity = (short)7
                        },
                        new
                        {
                            Id = 3,
                            AirlineId = 2,
                            Model = "Boeing 555",
                            SeatCapacity = (short)5
                        },
                        new
                        {
                            Id = 4,
                            AirlineId = 2,
                            Model = "Boeing 777",
                            SeatCapacity = (short)4
                        });
                });

            modelBuilder.Entity("DAL.models.Airport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Country")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Airports");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "CAI",
                            Name = "Cairo International Airport"
                        },
                        new
                        {
                            Id = 2,
                            Code = "DXB",
                            Name = "Dubai International Airport"
                        },
                        new
                        {
                            Id = 3,
                            Code = "DOH",
                            Name = "Doha International Airport"
                        },
                        new
                        {
                            Id = 4,
                            Code = "IST",
                            Name = "Istanbul Airport"
                        });
                });

            modelBuilder.Entity("DAL.models.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BookingDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("FlightId")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("PNR")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalPrice")
                        .HasPrecision(9, 2)
                        .HasColumnType("decimal(9,2)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("FlightId");

                    b.HasIndex("PNR")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("DAL.models.Flight", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AirlineId")
                        .HasColumnType("int");

                    b.Property<int>("AirplaneId")
                        .HasColumnType("int");

                    b.Property<int>("ArrivalAirportID")
                        .HasColumnType("int");

                    b.Property<DateTime>("ArrivalTime")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("BasePrice")
                        .HasPrecision(9, 2)
                        .HasColumnType("decimal(9,2)");

                    b.Property<int>("DepartureAirportID")
                        .HasColumnType("int");

                    b.Property<DateTime>("DepartureTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AirlineId");

                    b.HasIndex("AirplaneId");

                    b.HasIndex("ArrivalAirportID");

                    b.HasIndex("DepartureAirportID");

                    b.ToTable("Flights");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AirlineId = 1,
                            AirplaneId = 1,
                            ArrivalAirportID = 2,
                            ArrivalTime = new DateTime(2025, 1, 1, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            BasePrice = 2500m,
                            DepartureAirportID = 1,
                            DepartureTime = new DateTime(2025, 1, 1, 10, 30, 0, 0, DateTimeKind.Unspecified),
                            Status = 1
                        },
                        new
                        {
                            Id = 2,
                            AirlineId = 2,
                            AirplaneId = 2,
                            ArrivalAirportID = 3,
                            ArrivalTime = new DateTime(2025, 1, 12, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            BasePrice = 3200m,
                            DepartureAirportID = 2,
                            DepartureTime = new DateTime(2025, 1, 12, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1
                        },
                        new
                        {
                            Id = 3,
                            AirlineId = 4,
                            AirplaneId = 3,
                            ArrivalAirportID = 1,
                            ArrivalTime = new DateTime(2025, 1, 12, 6, 0, 0, 0, DateTimeKind.Unspecified),
                            BasePrice = 3200m,
                            DepartureAirportID = 3,
                            DepartureTime = new DateTime(2025, 1, 12, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1
                        },
                        new
                        {
                            Id = 4,
                            AirlineId = 3,
                            AirplaneId = 4,
                            ArrivalAirportID = 2,
                            ArrivalTime = new DateTime(2025, 1, 3, 6, 0, 0, 0, DateTimeKind.Unspecified),
                            BasePrice = 3200m,
                            DepartureAirportID = 4,
                            DepartureTime = new DateTime(2025, 1, 3, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1
                        },
                        new
                        {
                            Id = 5,
                            AirlineId = 2,
                            AirplaneId = 1,
                            ArrivalAirportID = 3,
                            ArrivalTime = new DateTime(2025, 1, 10, 6, 0, 0, 0, DateTimeKind.Unspecified),
                            BasePrice = 4900m,
                            DepartureAirportID = 1,
                            DepartureTime = new DateTime(2025, 1, 10, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1
                        },
                        new
                        {
                            Id = 6,
                            AirlineId = 4,
                            AirplaneId = 2,
                            ArrivalAirportID = 3,
                            ArrivalTime = new DateTime(2025, 1, 4, 6, 0, 0, 0, DateTimeKind.Unspecified),
                            BasePrice = 8200m,
                            DepartureAirportID = 2,
                            DepartureTime = new DateTime(2025, 1, 4, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1
                        },
                        new
                        {
                            Id = 7,
                            AirlineId = 2,
                            AirplaneId = 2,
                            ArrivalAirportID = 1,
                            ArrivalTime = new DateTime(2025, 2, 12, 6, 0, 0, 0, DateTimeKind.Unspecified),
                            BasePrice = 1200m,
                            DepartureAirportID = 3,
                            DepartureTime = new DateTime(2025, 2, 12, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1
                        },
                        new
                        {
                            Id = 8,
                            AirlineId = 1,
                            AirplaneId = 2,
                            ArrivalAirportID = 4,
                            ArrivalTime = new DateTime(2025, 4, 11, 6, 0, 0, 0, DateTimeKind.Unspecified),
                            BasePrice = 6200m,
                            DepartureAirportID = 3,
                            DepartureTime = new DateTime(2025, 4, 11, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1
                        },
                        new
                        {
                            Id = 9,
                            AirlineId = 2,
                            AirplaneId = 1,
                            ArrivalAirportID = 1,
                            ArrivalTime = new DateTime(2025, 5, 22, 6, 0, 0, 0, DateTimeKind.Unspecified),
                            BasePrice = 5300m,
                            DepartureAirportID = 2,
                            DepartureTime = new DateTime(2025, 5, 22, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1
                        },
                        new
                        {
                            Id = 10,
                            AirlineId = 3,
                            AirplaneId = 4,
                            ArrivalAirportID = 2,
                            ArrivalTime = new DateTime(2025, 7, 23, 6, 0, 0, 0, DateTimeKind.Unspecified),
                            BasePrice = 3500m,
                            DepartureAirportID = 4,
                            DepartureTime = new DateTime(2025, 7, 23, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1
                        },
                        new
                        {
                            Id = 11,
                            AirlineId = 3,
                            AirplaneId = 2,
                            ArrivalAirportID = 2,
                            ArrivalTime = new DateTime(2025, 1, 23, 6, 0, 0, 0, DateTimeKind.Unspecified),
                            BasePrice = 7600m,
                            DepartureAirportID = 3,
                            DepartureTime = new DateTime(2025, 1, 23, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1
                        },
                        new
                        {
                            Id = 12,
                            AirlineId = 4,
                            AirplaneId = 1,
                            ArrivalAirportID = 1,
                            ArrivalTime = new DateTime(2025, 9, 24, 6, 0, 0, 0, DateTimeKind.Unspecified),
                            BasePrice = 1500m,
                            DepartureAirportID = 2,
                            DepartureTime = new DateTime(2025, 9, 24, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1
                        });
                });

            modelBuilder.Entity("DAL.models.FlightSeat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("FlightId")
                        .HasColumnType("int");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<int>("SeatId")
                        .HasColumnType("int");

                    b.Property<int?>("TicketId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SeatId");

                    b.HasIndex("FlightId", "SeatId")
                        .IsUnique();

                    b.ToTable("FlightSeats");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FlightId = 1,
                            IsAvailable = true,
                            SeatId = 1
                        },
                        new
                        {
                            Id = 2,
                            FlightId = 1,
                            IsAvailable = true,
                            SeatId = 2
                        },
                        new
                        {
                            Id = 3,
                            FlightId = 1,
                            IsAvailable = true,
                            SeatId = 3
                        },
                        new
                        {
                            Id = 4,
                            FlightId = 1,
                            IsAvailable = true,
                            SeatId = 4
                        },
                        new
                        {
                            Id = 5,
                            FlightId = 1,
                            IsAvailable = true,
                            SeatId = 5
                        },
                        new
                        {
                            Id = 6,
                            FlightId = 1,
                            IsAvailable = true,
                            SeatId = 6
                        },
                        new
                        {
                            Id = 7,
                            FlightId = 1,
                            IsAvailable = true,
                            SeatId = 7
                        },
                        new
                        {
                            Id = 8,
                            FlightId = 1,
                            IsAvailable = true,
                            SeatId = 8
                        },
                        new
                        {
                            Id = 9,
                            FlightId = 2,
                            IsAvailable = true,
                            SeatId = 1
                        },
                        new
                        {
                            Id = 10,
                            FlightId = 2,
                            IsAvailable = true,
                            SeatId = 2
                        },
                        new
                        {
                            Id = 11,
                            FlightId = 2,
                            IsAvailable = true,
                            SeatId = 3
                        },
                        new
                        {
                            Id = 12,
                            FlightId = 2,
                            IsAvailable = true,
                            SeatId = 4
                        },
                        new
                        {
                            Id = 13,
                            FlightId = 2,
                            IsAvailable = true,
                            SeatId = 5
                        },
                        new
                        {
                            Id = 14,
                            FlightId = 2,
                            IsAvailable = true,
                            SeatId = 6
                        },
                        new
                        {
                            Id = 15,
                            FlightId = 2,
                            IsAvailable = true,
                            SeatId = 7
                        },
                        new
                        {
                            Id = 16,
                            FlightId = 3,
                            IsAvailable = true,
                            SeatId = 1
                        },
                        new
                        {
                            Id = 17,
                            FlightId = 3,
                            IsAvailable = true,
                            SeatId = 2
                        },
                        new
                        {
                            Id = 18,
                            FlightId = 3,
                            IsAvailable = true,
                            SeatId = 3
                        },
                        new
                        {
                            Id = 19,
                            FlightId = 3,
                            IsAvailable = true,
                            SeatId = 4
                        },
                        new
                        {
                            Id = 20,
                            FlightId = 3,
                            IsAvailable = true,
                            SeatId = 5
                        },
                        new
                        {
                            Id = 23,
                            FlightId = 4,
                            IsAvailable = true,
                            SeatId = 1
                        },
                        new
                        {
                            Id = 24,
                            FlightId = 4,
                            IsAvailable = true,
                            SeatId = 2
                        },
                        new
                        {
                            Id = 25,
                            FlightId = 4,
                            IsAvailable = true,
                            SeatId = 3
                        },
                        new
                        {
                            Id = 26,
                            FlightId = 4,
                            IsAvailable = true,
                            SeatId = 4
                        },
                        new
                        {
                            Id = 27,
                            FlightId = 5,
                            IsAvailable = true,
                            SeatId = 1
                        },
                        new
                        {
                            Id = 28,
                            FlightId = 5,
                            IsAvailable = true,
                            SeatId = 2
                        },
                        new
                        {
                            Id = 29,
                            FlightId = 5,
                            IsAvailable = true,
                            SeatId = 3
                        },
                        new
                        {
                            Id = 30,
                            FlightId = 5,
                            IsAvailable = true,
                            SeatId = 4
                        },
                        new
                        {
                            Id = 31,
                            FlightId = 5,
                            IsAvailable = true,
                            SeatId = 5
                        },
                        new
                        {
                            Id = 32,
                            FlightId = 5,
                            IsAvailable = true,
                            SeatId = 6
                        },
                        new
                        {
                            Id = 33,
                            FlightId = 5,
                            IsAvailable = true,
                            SeatId = 7
                        },
                        new
                        {
                            Id = 34,
                            FlightId = 5,
                            IsAvailable = true,
                            SeatId = 8
                        },
                        new
                        {
                            Id = 35,
                            FlightId = 6,
                            IsAvailable = true,
                            SeatId = 1
                        },
                        new
                        {
                            Id = 36,
                            FlightId = 6,
                            IsAvailable = true,
                            SeatId = 2
                        },
                        new
                        {
                            Id = 37,
                            FlightId = 6,
                            IsAvailable = true,
                            SeatId = 3
                        },
                        new
                        {
                            Id = 38,
                            FlightId = 6,
                            IsAvailable = true,
                            SeatId = 4
                        },
                        new
                        {
                            Id = 39,
                            FlightId = 6,
                            IsAvailable = true,
                            SeatId = 5
                        },
                        new
                        {
                            Id = 40,
                            FlightId = 6,
                            IsAvailable = true,
                            SeatId = 6
                        },
                        new
                        {
                            Id = 41,
                            FlightId = 6,
                            IsAvailable = true,
                            SeatId = 7
                        },
                        new
                        {
                            Id = 82,
                            FlightId = 7,
                            IsAvailable = true,
                            SeatId = 1
                        },
                        new
                        {
                            Id = 42,
                            FlightId = 7,
                            IsAvailable = true,
                            SeatId = 2
                        },
                        new
                        {
                            Id = 43,
                            FlightId = 7,
                            IsAvailable = true,
                            SeatId = 3
                        },
                        new
                        {
                            Id = 44,
                            FlightId = 7,
                            IsAvailable = true,
                            SeatId = 4
                        },
                        new
                        {
                            Id = 45,
                            FlightId = 7,
                            IsAvailable = true,
                            SeatId = 5
                        },
                        new
                        {
                            Id = 46,
                            FlightId = 7,
                            IsAvailable = true,
                            SeatId = 6
                        },
                        new
                        {
                            Id = 47,
                            FlightId = 7,
                            IsAvailable = true,
                            SeatId = 7
                        },
                        new
                        {
                            Id = 48,
                            FlightId = 8,
                            IsAvailable = true,
                            SeatId = 1
                        },
                        new
                        {
                            Id = 49,
                            FlightId = 8,
                            IsAvailable = true,
                            SeatId = 2
                        },
                        new
                        {
                            Id = 50,
                            FlightId = 8,
                            IsAvailable = true,
                            SeatId = 3
                        },
                        new
                        {
                            Id = 51,
                            FlightId = 8,
                            IsAvailable = true,
                            SeatId = 4
                        },
                        new
                        {
                            Id = 52,
                            FlightId = 8,
                            IsAvailable = true,
                            SeatId = 5
                        },
                        new
                        {
                            Id = 53,
                            FlightId = 8,
                            IsAvailable = true,
                            SeatId = 6
                        },
                        new
                        {
                            Id = 54,
                            FlightId = 8,
                            IsAvailable = true,
                            SeatId = 7
                        },
                        new
                        {
                            Id = 55,
                            FlightId = 9,
                            IsAvailable = true,
                            SeatId = 1
                        },
                        new
                        {
                            Id = 56,
                            FlightId = 9,
                            IsAvailable = true,
                            SeatId = 2
                        },
                        new
                        {
                            Id = 57,
                            FlightId = 9,
                            IsAvailable = true,
                            SeatId = 3
                        },
                        new
                        {
                            Id = 58,
                            FlightId = 9,
                            IsAvailable = true,
                            SeatId = 4
                        },
                        new
                        {
                            Id = 59,
                            FlightId = 9,
                            IsAvailable = true,
                            SeatId = 5
                        },
                        new
                        {
                            Id = 60,
                            FlightId = 9,
                            IsAvailable = true,
                            SeatId = 6
                        },
                        new
                        {
                            Id = 61,
                            FlightId = 9,
                            IsAvailable = true,
                            SeatId = 8
                        },
                        new
                        {
                            Id = 62,
                            FlightId = 9,
                            IsAvailable = true,
                            SeatId = 7
                        },
                        new
                        {
                            Id = 63,
                            FlightId = 10,
                            IsAvailable = true,
                            SeatId = 1
                        },
                        new
                        {
                            Id = 64,
                            FlightId = 10,
                            IsAvailable = true,
                            SeatId = 2
                        },
                        new
                        {
                            Id = 65,
                            FlightId = 10,
                            IsAvailable = true,
                            SeatId = 3
                        },
                        new
                        {
                            Id = 66,
                            FlightId = 10,
                            IsAvailable = true,
                            SeatId = 4
                        },
                        new
                        {
                            Id = 67,
                            FlightId = 11,
                            IsAvailable = true,
                            SeatId = 1
                        },
                        new
                        {
                            Id = 68,
                            FlightId = 11,
                            IsAvailable = true,
                            SeatId = 2
                        },
                        new
                        {
                            Id = 69,
                            FlightId = 11,
                            IsAvailable = true,
                            SeatId = 3
                        },
                        new
                        {
                            Id = 70,
                            FlightId = 11,
                            IsAvailable = true,
                            SeatId = 4
                        },
                        new
                        {
                            Id = 71,
                            FlightId = 11,
                            IsAvailable = true,
                            SeatId = 5
                        },
                        new
                        {
                            Id = 72,
                            FlightId = 11,
                            IsAvailable = true,
                            SeatId = 6
                        },
                        new
                        {
                            Id = 73,
                            FlightId = 11,
                            IsAvailable = true,
                            SeatId = 7
                        },
                        new
                        {
                            Id = 74,
                            FlightId = 12,
                            IsAvailable = true,
                            SeatId = 1
                        },
                        new
                        {
                            Id = 75,
                            FlightId = 12,
                            IsAvailable = true,
                            SeatId = 2
                        },
                        new
                        {
                            Id = 76,
                            FlightId = 12,
                            IsAvailable = true,
                            SeatId = 3
                        },
                        new
                        {
                            Id = 77,
                            FlightId = 12,
                            IsAvailable = true,
                            SeatId = 4
                        },
                        new
                        {
                            Id = 78,
                            FlightId = 12,
                            IsAvailable = true,
                            SeatId = 5
                        },
                        new
                        {
                            Id = 79,
                            FlightId = 12,
                            IsAvailable = true,
                            SeatId = 6
                        },
                        new
                        {
                            Id = 80,
                            FlightId = 12,
                            IsAvailable = true,
                            SeatId = 8
                        },
                        new
                        {
                            Id = 81,
                            FlightId = 12,
                            IsAvailable = true,
                            SeatId = 7
                        });
                });

            modelBuilder.Entity("DAL.models.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(9, 2)
                        .HasColumnType("decimal(9,2)");

                    b.Property<int>("BookingID")
                        .HasColumnType("int");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentIntentId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("PaymentStatus")
                        .HasColumnType("int");

                    b.Property<string>("SessionId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("BookingID")
                        .IsUnique();

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("DAL.models.Seat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AirplaneId")
                        .HasColumnType("int");

                    b.Property<int>("Class")
                        .HasColumnType("int");

                    b.Property<short>("Number")
                        .HasColumnType("smallint");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<string>("Row")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("AirplaneId");

                    b.ToTable("Seats");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AirplaneId = 1,
                            Class = 1,
                            Number = (short)1,
                            Price = 100,
                            Row = "A"
                        },
                        new
                        {
                            Id = 2,
                            AirplaneId = 1,
                            Class = 1,
                            Number = (short)2,
                            Price = 100,
                            Row = "A"
                        },
                        new
                        {
                            Id = 3,
                            AirplaneId = 1,
                            Class = 2,
                            Number = (short)1,
                            Price = 200,
                            Row = "B"
                        },
                        new
                        {
                            Id = 4,
                            AirplaneId = 1,
                            Class = 2,
                            Number = (short)2,
                            Price = 200,
                            Row = "B"
                        },
                        new
                        {
                            Id = 5,
                            AirplaneId = 1,
                            Class = 3,
                            Number = (short)1,
                            Price = 300,
                            Row = "C"
                        },
                        new
                        {
                            Id = 6,
                            AirplaneId = 1,
                            Class = 3,
                            Number = (short)2,
                            Price = 300,
                            Row = "C"
                        },
                        new
                        {
                            Id = 7,
                            AirplaneId = 1,
                            Class = 1,
                            Number = (short)1,
                            Price = 100,
                            Row = "D"
                        },
                        new
                        {
                            Id = 8,
                            AirplaneId = 1,
                            Class = 1,
                            Number = (short)2,
                            Price = 100,
                            Row = "D"
                        });
                });

            modelBuilder.Entity("DAL.models.Ticket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BookingID")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FlightSeatId")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PassportNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SeatId")
                        .HasColumnType("int");

                    b.Property<string>("TicketNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("TicketPrice")
                        .HasPrecision(9, 2)
                        .HasColumnType("decimal(9,2)");

                    b.HasKey("Id");

                    b.HasIndex("BookingID");

                    b.HasIndex("FlightSeatId")
                        .IsUnique();

                    b.HasIndex("SeatId");

                    b.HasIndex("TicketNumber")
                        .IsUnique();

                    b.ToTable("Tickets");
                });

            modelBuilder.Entity("DAL.models.TicketAddOns", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AddOnID")
                        .HasColumnType("int");

                    b.Property<int>("TicketId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AddOnID");

                    b.HasIndex("TicketId", "AddOnID")
                        .IsUnique();

                    b.ToTable("BookingAddOns");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("Roles", "Security");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("RoleClaims", "Security");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserClaims", "Security");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("UserLogins", "Security");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles", "Security");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("UserTokens", "Security");
                });

            modelBuilder.Entity("DAL.models.Airplane", b =>
                {
                    b.HasOne("DAL.models.Airline", "Airline")
                        .WithMany("Airplanes")
                        .HasForeignKey("AirlineId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Airline");
                });

            modelBuilder.Entity("DAL.models.Booking", b =>
                {
                    b.HasOne("DAL.models.Flight", "Flight")
                        .WithMany("Bookings")
                        .HasForeignKey("FlightId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("BAL.model.AppUser", "AppUser")
                        .WithMany("Bookings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("AppUser");

                    b.Navigation("Flight");
                });

            modelBuilder.Entity("DAL.models.Flight", b =>
                {
                    b.HasOne("DAL.models.Airline", "Airline")
                        .WithMany("Flights")
                        .HasForeignKey("AirlineId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("DAL.models.Airplane", "Airplane")
                        .WithMany("Flights")
                        .HasForeignKey("AirplaneId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("DAL.models.Airport", "ArrivalAirport")
                        .WithMany("ArrivalFlights")
                        .HasForeignKey("ArrivalAirportID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("DAL.models.Airport", "DepartureAirport")
                        .WithMany("DepartureFlights")
                        .HasForeignKey("DepartureAirportID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Airline");

                    b.Navigation("Airplane");

                    b.Navigation("ArrivalAirport");

                    b.Navigation("DepartureAirport");
                });

            modelBuilder.Entity("DAL.models.FlightSeat", b =>
                {
                    b.HasOne("DAL.models.Flight", "Flight")
                        .WithMany("FlightSeats")
                        .HasForeignKey("FlightId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DAL.models.Seat", "Seat")
                        .WithMany("FlightSeats")
                        .HasForeignKey("SeatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Flight");

                    b.Navigation("Seat");
                });

            modelBuilder.Entity("DAL.models.Payment", b =>
                {
                    b.HasOne("DAL.models.Booking", "Booking")
                        .WithOne("Payment")
                        .HasForeignKey("DAL.models.Payment", "BookingID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Booking");
                });

            modelBuilder.Entity("DAL.models.Seat", b =>
                {
                    b.HasOne("DAL.models.Airplane", "Airplane")
                        .WithMany("SeatTemplates")
                        .HasForeignKey("AirplaneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Airplane");
                });

            modelBuilder.Entity("DAL.models.Ticket", b =>
                {
                    b.HasOne("DAL.models.Booking", "Booking")
                        .WithMany("Tickets")
                        .HasForeignKey("BookingID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DAL.models.FlightSeat", "FlightSeat")
                        .WithOne("Ticket")
                        .HasForeignKey("DAL.models.Ticket", "FlightSeatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DAL.models.Seat", null)
                        .WithMany("Tickets")
                        .HasForeignKey("SeatId");

                    b.Navigation("Booking");

                    b.Navigation("FlightSeat");
                });

            modelBuilder.Entity("DAL.models.TicketAddOns", b =>
                {
                    b.HasOne("DAL.models.AddOn", "AddOn")
                        .WithMany("TicketAddOns")
                        .HasForeignKey("AddOnID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DAL.models.Ticket", "Ticket")
                        .WithMany("TicketAddOns")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AddOn");

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("BAL.model.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("BAL.model.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BAL.model.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("BAL.model.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BAL.model.AppUser", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("DAL.models.AddOn", b =>
                {
                    b.Navigation("TicketAddOns");
                });

            modelBuilder.Entity("DAL.models.Airline", b =>
                {
                    b.Navigation("Airplanes");

                    b.Navigation("Flights");
                });

            modelBuilder.Entity("DAL.models.Airplane", b =>
                {
                    b.Navigation("Flights");

                    b.Navigation("SeatTemplates");
                });

            modelBuilder.Entity("DAL.models.Airport", b =>
                {
                    b.Navigation("ArrivalFlights");

                    b.Navigation("DepartureFlights");
                });

            modelBuilder.Entity("DAL.models.Booking", b =>
                {
                    b.Navigation("Payment");

                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("DAL.models.Flight", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("FlightSeats");
                });

            modelBuilder.Entity("DAL.models.FlightSeat", b =>
                {
                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("DAL.models.Seat", b =>
                {
                    b.Navigation("FlightSeats");

                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("DAL.models.Ticket", b =>
                {
                    b.Navigation("TicketAddOns");
                });
#pragma warning restore 612, 618
        }
    }
}
